public with sharing class Clientcredwrapper {
    public String access_token;	//*******************
	public String instance_url;	//https://yourInstance.salesforce.com
	public String id;	//https://login.salesforce.com/id/XXXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXX
	public String token_type;	//Bearer
	public String scope;	//id api
	public String issued_at;	//1657741493799
	public String signature;	//c2lnbmF0dXJl
}