public with sharing class Devicewrapper {
    public String device_code;	//M01WRzlQaFI2ZzZCN3BzN1RUSTRjUDdNcHBnM2w3dHUuTVJBWVVMeVZxY21BOWhHTHBIaWlTLlE3ck​85eWpsbWZmaUJVTTZ0RnBZQWxYRWtSakhiOTsxMC4yMi4zNC45MjsxNDc3Njc0NDg3NTA1O1gxRDlTRUVU
	public String user_code;	//X1D9SEET
	public String verification_uri;	//https://acme.my.salesforce.com/setup/connect
	public Integer interval;

    public String access_token;	    //00DD00000008Uw2!ARkAQGppKf6n.VwG.EnFSvi731qWh.7vKfaJjL7h49yutIC84gAsxM​rqcE81GjpTjQbDLkytl2ZwosNbIJwUS0X8ahiILj3e
	public String refresh_token;	    //your token here
	public String signature;	    //hJuYICd2IHsjyTcFqTYiOr8THmgDmrcjgWaMp13X6dY=
	public String scope;	    //api
	public String instance_url;	    //https://yourInstance.salesforce.com
	public String id;	    //https://login.salesforce.com/id/00DD00000008Uw2MAE/005D0000001cAGmIAM
	public String token_type;	    //Bearer
	public String issued_at;	    //1477674717112

}

